stages:
  - test
  - build
  - deploy

unit-test:
  stage: test
  image: python:3.7-stretch
  before_script:
    - python3 -m pip install --no-cache-dir pipenv
    - pipenv install --system --dev
  script:
    - nosetests
    - pylint --exit-zero **/*.py

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
    - docker tag "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE/backend:latest"
    - docker push "$CI_REGISTRY_IMAGE/backend:latest"
  only:
    - master

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-master:
  stage: deploy
  image: google/cloud-sdk:latest
  variables:
    GCP_PROJECT_ID: avid-stone-229006
    GKE_CLUSTER_NAME: gitlab-cluster
    GKE_CLUSTER_ZONE: us-central1-a
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json  || die "unable to authenticate service account for gcloud"
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE --project $GCP_PROJECT_ID
    - kubectl version
  script:
    - kubectl --namespace=soarcast delete deployment soarcast-backend
    - kubectl apply -f k8s/app.yml
  only:
    - master